#!/usr/bin/env bash
#
# ~/.bashrc
#
# vim: set foldmethod=indent ai ts=4 sw=4 tw=79:

# shellcheck disable=SC2155

# User specific aliases and functions

export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
	#shellcheck disable=SC1091
	. /etc/bashrc
fi

# User specific environment and startup programs

#source /etc/profile.d/vte.sh

## Command not found
#source /usr/share/doc/pkgfile/command-not-found.bash
# Auto "cd" when entering just a path
shopt -s autocd
## Autojump
#source /etc/profile.d/autojump.bash

bind "set completion-ignore-case on"
bind Space:magic-space

# Share history between consoles
export HISTFILESIZE=10000
export HISTSIZE=5000
export HISTCONTROL=ignoreboth

ignore_prefixes=('exit' 'hist' 'echo' 'man' 'ls' 'pikaur -Syu'
	'sudo pacman -Syu' 'cd' 'less' 'htop' 'cls' 'which' 'type'
	'kill' 'whoami' 'xprop' 'obxprop' 'pkgfile'
	'pgg')
prefixes=""
for arg in "${ignore_prefixes[@]}"; do
	[ -n "$prefixes" ] && prefixes="${prefixes}:${arg}" || prefixes="$arg"
done

export HISTIGNORE="&:[ ]*:$prefixes"
#export HISTTIMEFORMAT='%F %T  '

shopt -s histappend
shopt -s histverify

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#export TERM="xterm-256color"
[ -n "$XTERM_VERSION" ] && transset-df --id "$WINDOWID" 0.90 >/dev/null

# Laisser à la fin !
#. /etc/profile.d/vte.sh

## Running under xterm ?
#[ -n "${XTERM_VERSION}" ] && return 0

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Bash completion

# pip bash completion start
_pip_completion() {
	# shellcheck disable=SC2207
	COMPREPLY=($(COMP_WORDS="${COMP_WORDS[*]}" \
		COMP_CWORD=$COMP_CWORD \
		PIP_AUTO_COMPLETE=1 $1))
}
complete -o default -F _pip_completion pip
# pip bash completion end

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Prompt
# shellcheck disable=SC1090
#source "$HOME/.prompt"

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Bash It

# Path to the bash it configuration
export BASH_IT="/home/canalguada/git/bash-it"

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
export SHORT_HOSTNAME=$(hostname -s)

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
# shellcheck disable=SC1090
[ -f $BASH_IT/bash_it.sh ] && source $BASH_IT/bash_it.sh

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# Force dark GTK theme
#[ -f ~/.dark-gtk/build.sh ] && . ~/.dark-gtk/build.sh

#disable-proxy

#wq qotd 2>/dev/null

# Starship
#eval "$(starship init bash)"

# Only load Liquid Prompt in interactive shells, not from a script or from scp
#[[ $- = *i* ]] && source /usr/bin/liquidprompt

eval "$(fasd --init auto)"

## Set up Node Version Manager
#source /usr/share/nvm/init-nvm.sh

#export NVM_DIR="$HOME/.config/nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

systemctl --user import-environment PATH

# Only load liquidprompt in interactive shells, not from a script or from scp
echo $- | grep -q i 2>/dev/null && . /usr/share/liquidprompt/liquidprompt

