#!/usr/bin/sh
# vim: set ft=sh ai ts=2 sw=2 tw=79 noet:

[ $# -ge 2 ] || exit 1

# # grep -oP "set [$]ws[[:digit:]]+.*" ~/.config/i3/config \
# # |sed 's/set \$\([^[:blank:]]*\)[[:blank:]]*\(.*\)/\1=\2/g'
# ws1=1:
# ws2=2:
# ws3=3:
# ws4=4:
# ws5=5:
# ws6=6:
# ws7=7:
# ws8=8:
# ws9=9:
# ws10=10:

ws=$1
shift

focused="/tmp/$USER/i3/cache/focused"
[ ! -d "$(dirname "$focused")" ] &&
  mkdir -p "$(dirname "$focused")"

get_focused_ws () {
	jq_filter='.[] | { name: .name, focused: .focused } | 
	select(.focused == true) | .name'
	i3-msg -t get_workspaces | \
		jq -r "$jq_filter" >"$focused"
}

get_focused_ws &
pid=$!
cmd=$(pyquote "$@")
unset msg
wait $pid
[ "$ws" != "$(head -n1 $focused)" ] &&
	msg='workspace "'$ws'"; '
msg="${msg}exec $cmd"

i3-msg "$msg" >/dev/null 2>&1
